import React from 'react'

import { Helmet } from 'react-helmet'

import HomepageNavbar from '../components/homepage-navbar'
import Footer from '../components/footer'
import projectStyles from '../style.module.css'
import styles from './privacy-policy.module.css'

const PrivacyPolicy = () => {
  return (
    <div className={styles['container']}>
      <Helmet>
        <title>
          privacy-policy - Kajoo - Build Sitecore pages visually in minutes
        </title>
        <meta
          name="description"
          content="Kajoo takes care of the tedious part of working with Sitecore. Give it a design and watch it convert it to a functioning page in minutes. "
        />
        <meta
          property="og:title"
          content="privacy-policy - Kajoo - Build Sitecore pages visually in minutes"
        />
        <meta
          property="og:description"
          content="Kajoo takes care of the tedious part of working with Sitecore. Give it a design and watch it convert it to a functioning page in minutes. "
        />
        <meta
          property="og:image"
          content="https://aheioqhobo.cloudimg.io/v7/_playground-bucket-v2.teleporthq.io_/a38aa983-2408-4700-bd13-f066aeb36eea/83457e41-6b15-49f4-9906-02b66d9d751f?org_if_sml=1"
        />
      </Helmet>
      <HomepageNavbar rootClassName="rootClassName3"></HomepageNavbar>
      <div className={styles['container1']}>
        <h1 className={` ${styles['text']} ${projectStyles['heading1']} `}>
          <span>Privacy Policy</span>
        </h1>
        <span className={` ${styles['text002']} ${projectStyles['body2']} `}>
          <span></span>
          <span>E</span>
          <span>ffective date: August 07, 2019</span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            TechGuilds Consulting Inc. (&quot;us&quot;, &quot;we&quot;, or
            &quot;our&quot;) operates the / website (hereinafter referred to as
            the &quot;Service&quot;).
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            This page informs you of our policies regarding the collection, use
            and disclosure of personal data when you use our Service and the
            choices you have associated with that data.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            We use your data to provide and improve the Service. By using the
            Service, you agree to the collection and use of information in
            accordance with this policy. Unless otherwise defined in this
            Privacy Policy, the terms used in this Privacy Policy have the same
            meanings as in our Terms and Conditions, accessible from
          </span>
          <span></span>
        </span>
        <h2 className={` ${styles['text013']} ${projectStyles['heading21']} `}>
          <span>Definitions</span>
        </h2>
        <span className={` ${styles['text015']} ${projectStyles['body2']} `}>
          <span className={styles['text016']}>Service</span>
          <br></br>
          <span></span>
          <span>
            Service is the / website operated by TechGuilds Consulting Inc.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>​</span>
          <span className={styles['text022']}></span>
          <span className={styles['text023']}>Personal Data</span>
          <br></br>
          <span></span>
          <span>
            Personal Data means data about a living individual who can be
            identified from those data (or from those and other information
            either in our possession or likely to come into our possession).
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text027']}>Usage Data</span>
          <br></br>
          <span></span>
          <span>
            Usage Data is data collected automatically either generated by the
            use of the Service or from the Service infrastructure itself (for
            example, the duration of a page visit).
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text031']}>Cookies</span>
          <br></br>
          <span></span>
          <span>
            Cookies are small files stored on your device (computer or mobile
            device).
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text035']}>Data Controller</span>
          <br></br>
          <span></span>
          <span>
            Data Controller means the natural or legal person who (either alone
            or jointly or in common with other persons) determines the purposes
            for which and the manner in which any personal information are, or
            are to be, processed.
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span></span>
          <span>
            For the purpose of this Privacy Policy, we are a Data Controller of
            your Personal Data.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text041']}>
            Data Processors (or Service Providers)
          </span>
          <br></br>
          <span></span>
          <span>
            Data Processor (or Service Provider) means any natural or legal
            person who processes the data on behalf of the Data Controller. We
            may use the services of various Service Providers in order to
            process your data more effectively.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span></span>
          <span className={styles['text046']}>Data Subject (or User)</span>
          <span className={styles['text047']}></span>
          <span className={styles['text048']}></span>
          <br></br>
          <span>
            Data Subject is any living individual who is using our Service and
            is the subject of Personal Data.
          </span>
          <br></br>
        </span>
        <h2 className={` ${styles['text050']} ${projectStyles['heading21']} `}>
          <span>Information Collection and Use</span>
        </h2>
        <span
          className={` ${styles['text052']} ${projectStyles['body2']} `}
        ></span>
        <h3 className={` ${styles['text053']} ${projectStyles['heading3']} `}>
          <span>Types of Data Collected</span>
        </h3>
        <span className={` ${styles['text055']} ${projectStyles['body2']} `}>
          <span className={styles['text056']}>Personal Data</span>
          <br></br>
          <span>​</span>
          <span>
            While using our Service, we may ask you to provide us with certain
            personally identifiable information that can be used to contact or
            identify you (&quot;Personal Data&quot;). Personally identifiable
            information may include, but is not limited to:
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>- Email address</span>
          <br></br>
          <span>- First name and last name</span>
          <br></br>
          <span>- Phone number</span>
          <br></br>
          <span>- Address, State, Province, ZIP/Postal code, City</span>
          <br></br>
          <span>- Cookies and Usage Data</span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            We may use your Personal Data to contact you with newsletters,
            marketing or promotional materials and other information that may be
            of interest to you. You may opt out of receiving any, or all, of
            these communications from us by following the unsubscribe link or
            the instructions provided in any email we send.
          </span>
          <br></br>
          <span>​</span>
          <br></br>
          <span className={styles['text071']}>Usage Data</span>
          <br></br>
          <span></span>
          <span>
            We may also collect information on how the Service is accessed and
            used (&quot;Usage Data&quot;). This Usage Data may include
            information such as your computer&apos;s Internet Protocol address
            (e.g. IP address), browser type, browser version, the pages of our
            Service that you visit, the time and date of your visit, the time
            spent on those pages, unique device identifiers and other diagnostic
            data.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text076']}>Tracking &amp; Cookies Data</span>
          <br></br>
          <span></span>
          <span>
            We use cookies and similar tracking technologies to track the
            activity on our Service and we hold certain information.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            Cookies are files with a small amount of data which may include an
            anonymous unique identifier. Cookies are sent to your browser from a
            website and stored on your device. Other tracking technologies are
            also used such as beacons, tags and scripts to collect and track
            information and to improve and analyse our Service.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            You can instruct your browser to refuse all cookies or to indicate
            when a cookie is being sent. However, if you do not accept cookies,
            you may not be able to use some portions of our Service.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>Examples of Cookies we use:</span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>
            Session Cookies. We use Session Cookies to operate our Service.
          </span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>
            Preference Cookies. We use Preference Cookies to remember your
            preferences and various settings.
          </span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>
            Security Cookies. We use Security Cookies for security purposes.
          </span>
          <span></span>
        </span>
        <h3 className={` ${styles['text094']} ${projectStyles['heading3']} `}>
          <span>Use of Data</span>
        </h3>
        <span className={` ${styles['text096']} ${projectStyles['body2']} `}>
          <span>
            TechGuilds Consulting Inc. uses the collected data for various
            purposes:
          </span>
          <span></span>
          <br></br>
          <span>- To provide and maintain our Service</span>
          <br></br>
          <span>- To notify you about changes to our Service</span>
          <br></br>
          <span>
            - To allow you to participate in interactive features of our Service
            when you choose to do so
          </span>
          <br></br>
          <span>- To provide customer support</span>
          <br></br>
          <span>
            - To gather analysis or valuable information so that we can improve
            our Service
          </span>
          <br></br>
          <span>- To monitor the usage of our Service</span>
          <br></br>
          <span>- To detect, prevent and address technical issues</span>
          <br></br>
          <span>
            - To provide you with news, special offers and general information
            about other goods, services and events which we offer that are
            similar to those that you have already purchased or enquired about
            unless you have opted not to receive such information
          </span>
          <span></span>
        </span>
        <h3 className={` ${styles['text108']} ${projectStyles['heading3']} `}>
          <span>
            Legal Basis for Processing Personal Data under the General Data
            Protection Regulation (GDPR)
          </span>
        </h3>
        <span className={` ${styles['text110']} ${projectStyles['body2']} `}>
          <span></span>
          <span>
            If you are from the European Economic Area (EEA), TechGuilds
            Consulting Inc. legal basis for collecting and using the personal
            information described in this Privacy Policy depends on the Personal
            Data we collect and the specific context in which we collect it.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            TechGuilds Consulting Inc. may process your Personal Data because:
          </span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span></span>
          <span>We need to perform a contract with you</span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>You have given us permission to do so</span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>
            The processing is in our legitimate interests and it is not
            overridden by your rights
          </span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>To comply with the law</span>
        </span>
        <h3 className={` ${styles['text128']} ${projectStyles['heading3']} `}>
          <span>Retention of Data</span>
        </h3>
        <span className={` ${styles['text130']} ${projectStyles['body2']} `}>
          <span>
            TechGuilds Consulting Inc. will retain your Personal Data only for
            as long as is necessary for the purposes set out in this Privacy
            Policy. We will retain and use your Personal Data to the extent
            necessary to comply with our legal obligations (for example, if we
            are required to retain your data to comply with applicable laws),
            resolve disputes and enforce our legal agreements and policies.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            TechGuilds Consulting Inc. will also retain Usage Data for internal
            analysis purposes. Usage Data is generally retained for a shorter
            period of time, except when this data is used to strengthen the
            security or to improve the functionality of our Service, or we are
            legally obligated to retain this data for longer periods.
          </span>
          <span></span>
        </span>
        <h3 className={` ${styles['text135']} ${projectStyles['heading3']} `}>
          <span>Transfer of Data</span>
        </h3>
        <span className={` ${styles['text137']} ${projectStyles['body2']} `}>
          <span>
            Your information, including Personal Data, may be transferred to -
            and maintained on - computers located outside of your state,
            province, country or other governmental jurisdiction where the data
            protection laws may differ from those of your jurisdiction.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            If you are located outside Canada and choose to provide information
            to us, please note that we transfer the data, including Personal
            Data, to Canada and process it there.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            Your consent to this Privacy Policy followed by your submission of
            such information represents your agreement to that transfer.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            TechGuilds Consulting Inc. will take all the steps reasonably
            necessary to ensure that your data is treated securely and in
            accordance with this Privacy Policy and no transfer of your Personal
            Data will take place to an organisation or a country unless there
            are adequate controls in place including the security of your data
            and other personal information.
          </span>
        </span>
        <h3 className={` ${styles['text145']} ${projectStyles['heading3']} `}>
          <span>Disclosure of Data</span>
        </h3>
        <span className={` ${styles['text147']} ${projectStyles['body2']} `}>
          <span className={styles['text148']}>Business Transaction</span>
          <br></br>
          <span></span>
          <span>
            If TechGuilds Consulting Inc. is involved in a merger, acquisition
            or asset sale, your Personal Data may be transferred. We will
            provide notice before your Personal Data is transferred and becomes
            subject to a different Privacy Policy.
          </span>
          <br></br>
          <span className={styles['text152']}>&amp;#8203;</span>
          <br></br>
          <span className={styles['text153']}>Legal Requirements</span>
          <br></br>
          <span></span>
          <span>
            TechGuilds Consulting Inc. may disclose your Personal Data in the
            good faith belief that such action is necessary to:
          </span>
          <br></br>
          <span>
            -
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>To comply with a legal obligation</span>
          <br></br>
          <span>
            - To protect and defend the rights or property of TechGuilds
            Consulting Inc.
          </span>
          <br></br>
          <span>
            - To prevent or investigate possible wrongdoing in connection with
            the Service
          </span>
          <br></br>
          <span>
            - To protect the personal safety of users of the Service or the
            public
          </span>
          <br></br>
          <span>- To protect against legal liability</span>
        </span>
        <h3 className={` ${styles['text162']} ${projectStyles['heading3']} `}>
          <span>Security of Data</span>
        </h3>
        <span className={` ${styles['text164']} ${projectStyles['body2']} `}>
          <span>
            The security of your data is important to us but remember that no
            method of transmission over the Internet or method of electronic
            storage is 100% secure. While we strive to use commercially
            acceptable means to protect your Personal Data, we cannot guarantee
            its absolute security.
          </span>
        </span>
        <h3 className={` ${styles['text166']} ${projectStyles['heading3']} `}>
          <span>
            Our Policy on &quot;Do Not Track&quot; Signals under the California
            Online Protection Act (CalOPPA)
          </span>
        </h3>
        <span className={` ${styles['text168']} ${projectStyles['body2']} `}>
          <span>
            We do not support Do Not Track (&quot;DNT&quot;). Do Not Track is a
            preference you can set in your web browser to inform websites that
            you do not want to be tracked.
            <span
              dangerouslySetInnerHTML={{
                __html: ' ',
              }}
            />
          </span>
          <span>
            You can enable or disable Do Not Track by visiting the Preferences
            or Settings page of your web browser.
          </span>
        </span>
        <h3 className={` ${styles['text171']} ${projectStyles['heading3']} `}>
          <span>
            Your Data Protection Rights under the General Data Protection
            Regulation (GDPR)
          </span>
        </h3>
        <span className={` ${styles['text173']} ${projectStyles['body2']} `}>
          <span>
            If you are a resident of the European Economic Area (EEA), you have
            certain data protection rights. TechGuilds Consulting Inc. aims to
            take reasonable steps to allow you to correct, amend, delete or
            limit the use of your Personal Data.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            If you wish to be informed about what Personal Data we hold about
            you and if you want it to be removed from our systems, please
            contact us.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            In certain circumstances, you have the following data protection
            rights:
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text180']}>
            The right to access, update or delete the information we have on
            you.
          </span>
          <span>
            {' '}
            Whenever made possible, you can access, update or request deletion
            of your Personal Data directly within your account settings section.
            If you are unable to perform these actions yourself, please contact
            us to assist you.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text183']}>The right of rectification.</span>
          <span>
            {' '}
            You have the right to have your information rectified if that
            information is inaccurate or incomplete.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span></span>
          <span className={styles['text188']}>The right to object.</span>
          <span>
            {' '}
            You have the right to object to our processing of your Personal
            Data.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text191']}>The right of restriction.</span>
          <span>
            {' '}
            You have the right to request that we restrict the processing of
            your personal information.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text194']}>
            The right to data portability.
          </span>
          <span>
            {' '}
            You have the right to be provided with a copy of the information we
            have on you in a structured, machine-readable and commonly used
            format.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text197']}>
            The right to withdraw consent.
          </span>
          <span>
            {' '}
            You also have the right to withdraw your consent at any time where
            TechGuilds Consulting Inc. relied on your consent to process your
            personal information.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            Please note that we may ask you to verify your identity before
            responding to such requests.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            You have the right to complain to a Data Protection Authority about
            our collection and use of your Personal Data. For more information,
            please contact your local data protection authority in the European
            Economic Area (EEA).
          </span>
          <br></br>
          <span></span>
        </span>
        <h2 className={` ${styles['text204']} ${projectStyles['heading21']} `}>
          <span>Service Providers</span>
        </h2>
        <span className={` ${styles['text206']} ${projectStyles['body2']} `}>
          <span></span>
          <span></span>
          <span>
            We may employ third party companies and individuals to facilitate
            our Service (&quot;Service Providers&quot;), provide the Service on
            our behalf, perform Service-related services or assist us in
            analysing how our Service is used.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            These third parties have access to your Personal Data only to
            perform these tasks on our behalf and are obligated not to disclose
            or use it for any other purpose.
          </span>
          <span></span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text216']}>Analytics</span>
          <br></br>
          <span></span>
          <span>
            We may use third-party Service Providers to monitor and analyse the
            use of our Service.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text221']}>Google Analytics</span>
          <br></br>
          <span></span>
          <span>
            Google Analytics is a web analytics service offered by Google that
            tracks and reports website traffic. Google uses the data collected
            to track and monitor the use of our Service. This data is shared
            with other Google services. Google may use the collected data to
            contextualise and personalise the ads of its own advertising
            network.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            You can opt-out of having made your activity on the Service
            available to Google Analytics by installing the Google Analytics
            opt-out browser add-on. The add-on prevents the Google Analytics
            JavaScript (ga.js, analytics.js and dc.js) from sharing information
            with Google Analytics about visits activity.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            For more information on the privacy practices of Google, please
            visit the Google Privacy &amp; Terms web page:
            https://policies.google.com/privacy?hl=en
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text229']}>Behavioral Remarketing</span>
          <br></br>
          <span></span>
          <span>
            TechGuilds Consulting Inc. uses remarketing services to advertise on
            third party websites to you after you visited our Service. We and
            our third-party vendors use cookies to inform, optimise and serve
            ads based on your past visits to our Service.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span className={styles['text233']}>Google Ads (AdWords)</span>
          <br></br>
          <span></span>
          <span>
            Google Ads (AdWords) remarketing service is provided by Google Inc.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            You can opt-out of Google Analytics for Display Advertising and
            customise the Google Display Network ads by visiting the Google Ads
            Settings page: http://www.google.com/settings/ads
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            Google also recommends installing the Google Analytics Opt-out
            Browser Add-on - https://tools.google.com/dlpage/gaoptout - for your
            web browser. Google Analytics Opt-out Browser Add-on provides
            visitors with the ability to prevent their data from being collected
            and used by Google Analytics.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            For more information on the privacy practices of Google, please
            visit the Google Privacy &amp; Terms web page:
            https://policies.google.com/privacy?hl=en
          </span>
          <span></span>
        </span>
        <h2 className={` ${styles['text243']} ${projectStyles['heading21']} `}>
          <span>Links to Other Sites</span>
        </h2>
        <span className={` ${styles['text245']} ${projectStyles['body2']} `}>
          <span>
            Our Service may contain links to other sites that are not operated
            by us. If you click a third party link, you will be directed to that
            third party&apos;s site. We strongly advise you to review the
            Privacy Policy of every site you visit.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            We have no control over and assume no responsibility for the
            content, privacy policies or practices of any third party sites or
            services.
          </span>
          <span></span>
        </span>
        <h2 className={` ${styles['text250']} ${projectStyles['heading21']} `}>
          <span>Children&apos;s Privacy</span>
        </h2>
        <span className={` ${styles['text252']} ${projectStyles['body2']} `}>
          <span>
            Our Service does not address anyone under the age of 18
            (&quot;Children&quot;).
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            We do not knowingly collect personally identifiable information from
            anyone under the age of 18. If you are a parent or guardian and you
            are aware that your Child has provided us with Personal Data, please
            contact us. If we become aware that we have collected Personal Data
            from children without verification of parental consent, we take
            steps to remove that information from our servers.
          </span>
          <br></br>
          <span></span>
        </span>
        <h2 className={` ${styles['text257']} ${projectStyles['heading21']} `}>
          <span>Changes to This Privacy Policy</span>
        </h2>
        <span className={` ${styles['text259']} ${projectStyles['body2']} `}>
          <span>
            We may update our Privacy Policy from time to time. We will notify
            you of any changes by posting the new Privacy Policy on this page.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            We will let you know via email and/or a prominent notice on our
            Service, prior to the change becoming effective and update the
            &quot;effective date&quot; at the top of this Privacy Policy.
          </span>
          <br></br>
          <span></span>
          <br></br>
          <span>
            You are advised to review this Privacy Policy periodically for any
            changes. Changes to this Privacy Policy are effective when they are
            posted on this page.
          </span>
          <br></br>
          <span></span>
        </span>
        <h2 className={` ${styles['text266']} ${projectStyles['heading21']} `}>
          <span>Contact Us</span>
        </h2>
        <span className={` ${styles['text268']} ${projectStyles['body2']} `}>
          <span>
            If you have any questions about this Privacy Policy, please contact
            us b
          </span>
          <span></span>
          <span>y email: engage@techguilds.com</span>
        </span>
      </div>
      <div className={styles['section-separator']}></div>
      <Footer rootClassName="rootClassName1"></Footer>
    </div>
  )
}

export default PrivacyPolicy
